# Generated by Django 4.2.5 on 2023-09-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_startups_alter_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'permissions': [('can_create_post', 'Can create a new blog post'), ('can_edit_post', 'Can edit an existing blog post'), ('can_delete_post', 'Can delete a blog post'), ('view_future_post', 'Can view unpublished Post')], 'verbose_name': 'Blog Post'},
        ),
    ]
