# Generated by Django 4.2.3 on 2023-08-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslink',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date'], 'verbose_name': 'News Article'},
        ),
        migrations.AlterField(
            model_name='startup',
            name='tags',
            field=models.ManyToManyField(blank=True, to='organizer.tag'),
        ),
    ]
