# Generated by Django 4.2.5 on 2023-09-19 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0002_alter_newslink_options_alter_startup_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="startup",
            options={
                "get_latest_by": "founded_date",
                "ordering": ["name"],
                "permissions": [("startup_create", "Can Create Startup")],
            },
        ),
    ]
