# Generated by Django 4.2.5 on 2023-09-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="your email", max_length=254),
        ),
        migrations.AddField(
            model_name="profile",
            name="job",
            field=models.CharField(default="your degree", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter your phone number in the format '123-456-7890'",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to="profiles/"
            ),
        ),
    ]
